#!/bin/bash

echo "🚀 CONFIGURANDO GITHUB PAGES - DOCE SENSACOES"
echo "=============================================="

echo ""
echo "✅ ARQUIVOS PRONTOS!"
echo "==================="
echo "📁 Repositório: https://github.com/gopedrow/doce-sensacoes-frontend"
echo "📂 Pasta public: Configurada com todos os arquivos"
echo "🔗 Backend: https://doce-sensacoes-backend-17.onrender.com"
echo ""

echo "🎯 PRÓXIMOS PASSOS NO GITHUB:"
echo "============================="
echo ""
echo "1. 🌐 Acesse: https://github.com/gopedrow/doce-sensacoes-frontend"
echo ""
echo "2. ⚙️ Vá em Settings:"
echo "   - Clique na aba 'Settings'"
echo "   - Role até encontrar 'Pages' no menu lateral"
echo ""
echo "3. 📁 Configure o Source:"
echo "   - Em 'Source', selecione 'Deploy from a branch'"
echo "   - Em 'Branch', selecione 'main'"
echo "   - Em 'Folder', selecione '/public'"
echo "   - Clique em 'Save'"
echo ""
echo "4. ⏳ Aguarde alguns minutos para o deploy"
echo ""
echo "🔗 URL FINAL:"
echo "============"
echo "https://gopedrow.github.io/doce-sensacoes-frontend"
echo ""
echo "🧪 TESTE APÓS PUBLICAR:"
echo "======================"
echo "✅ Acesse a URL"
echo "✅ Teste cadastro de usuário"
echo "✅ Teste login"
echo "✅ Teste no celular"
echo ""
echo "🎉 PRONTO! Seu site ficará online!"
echo ""
echo "📞 Se tiver problemas:"
echo "1. Verifique se o backend está funcionando: node backend/testar-api.js"
echo "2. Confirme se todos os arquivos estão na pasta public"
echo "3. Aguarde alguns minutos para o GitHub Pages processar" 